name: 'Custom Python GitHub Action'
description: 'Calls Python script'
author: martoc
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: call script
      id: aws-call
      run: python ${{ github.action_path }}/src/aws-call.py
      shell: bash